;;;;;;;;;;;;; base app U ;;;;;;;;;;;;;;

[cont1]
file=\tmptitle_icon.ash
type=ASH|U8

[cont2]
file=\www.arc
type=ASH|U8

[cont3]
file=\corrupt_icon.ash
type=ASH|U8

[cont4]
file=\layout\common\address.ash
type=ASH|U8

[cont5]
file=\layout\common\balloon.ash
type=ASH|U8

[cont6]
file=\layout\common\board.ash
type=ASH|U8

[cont7]
file=\layout\common\calendar.ash
type=ASH|U8

[cont8]
file=\layout\common\chanEdit.ash
type=ASH|U8

[cont9]
file=\layout\common\chanSel.ash
type=ASH|U8

[cont10]
file=\layout\common\chanTtl.ash
type=ASH|U8

[cont11]
file=\layout\common\cmnbtn.ash
type=ASH|U8

[cont12]
file=\layout\common\cursor.ash
type=ASH|U8

[cont13]
file=\layout\common\diskBann.ash
type=ASH|U8

[cont14]
file=\layout\common\diskThum.ash
type=ASH|U8

[cont15]
file=\layout\common\dlgwdw.ash
type=ASH|U8

[cont16]
file=\layout\common\exbtn.ash
type=ASH|U8

[cont17]
file=\layout\common\faceSel.ash
type=ASH|U8

[cont18]
file=\layout\common\GCBann.ash
type=ASH|U8

[cont19]
file=\layout\common\gcMem.ash
type=ASH|U8

[cont20]
file=\layout\common\health.ash
type=ASH|U8

[cont21]
file=\layout\common\homebtn1.ash
type=ASH|U8

[cont22]
file=\layout\common\letter.ash
type=ASH|U8

[cont23]
file=\layout\common\limitOver.ash
type=ASH|U8

[cont24]
file=\layout\common\memory.ash
type=ASH|U8

[cont25]
file=\layout\common\mlAdSel.ash
type=ASH|U8

[cont26]
file=\layout\common\prntDlg.ash
type=ASH|U8

[cont27]
file=\layout\common\sdButton.ash
type=ASH|U8

[cont28]
file=\layout\common\sdchanSel.ash
type=ASH|U8

[cont29]
file=\layout\common\sdchanTtl.ash
type=ASH|U8

[cont30]
file=\layout\common\setting.ash
type=ASH|U8

[cont31]
file=\layout\common\setupBg.ash
type=ASH|U8

[cont32]
file=\layout\common\setupBtn.ash
type=ASH|U8

[cont33]
file=\layout\common\setupSel.ash
type=ASH|U8

[cont34]
file=\layout\common\sofkeybd.ash
type=ASH|U8

[cont35]
file=\layout\common\wiiMem.ash
type=ASH|U8

[cont36]
file=\layout\eng\homebtn1.ash
type=ASH|U8

[cont37]
file=\layout\common\diskBann2.ash
type=ASH|U8

[cont38]
file=\layout\common\setupSel2.ash
type=ASH|U8

[cont39]
file=\layout\common\
type=ASH|U8

;[cont]
;file=\layout\common\
;type=ASH|U8
